### ISSUE TITLE
In arabic layout  story progress going wrong  reverse..can u pls explain how fix that issue??

### ISSUE THREAD

**Issue by libzantz123** [c2mInc/C2MStoryViewer#4]

**Comment by Cutta** [comment]
Hi @libzantz123 
you can rotate 180-degree progress Views and change the start index with the last index. And you should decrease the index after every story watch.

**Comment by libzantz123** [comment]
TECH GOD 😘😘😘 thanks for your valuable reply..

**Comment by Odai773** [comment]
Please i want to revert the progress bar and cube transformation to be in arabic (froim right to left) any one can help ?

**Comment by Odai773** [comment]
@libzantz123 Did you have some steps to do for solving this issue

**Comment by libzantz123** [comment]
Yes, I did.
