### ISSUE TITLE
Story progress issue on image loading

### ISSUE THREAD

**Issue by jayeshkananidifferenz** [c2mInc/C2MStoryViewer#8]
Hello,

I am trying to load images using Glide library. When high resolution images are downloading, at that time Story Progress view is not working properly. Sometimes, Story progress is moved to another story before image displaying.
Here, I wants to pausing the story progressbar while downloading the image, and when image is displayed properly, at that time Story Progressbar should be working.

So, How can I pause the Story progress while downloading the images using Glide library?

**Comment by Cutta** [comment]
Hi,
You can pause the current story before loading with  pauseCurrentStory()
Add a listener to Glide to determine the exact time when the image load finished.
If you catch the finish statement call resumeCurrentStory()

**Comment by jayeshkananidifferenz** [comment]
> Hi,
> You can pause the current story before loading with pauseCurrentStory()
> Add a listener to Glide to determine the exact time when the image load finished.
> If you catch the finish statement call resumeCurrentStory()

@Cutta , Thanks for your response!
I have already tried this solution. Here, I've faced problem on onStartProgress() from PausableProgressBar.Callback.
Here, images loading process is started before executing onStartProgress() mehtod. In this method, current story index is retrieved.
Whenever, I called pauseCurrentStory(), its not working properly due to index issue from onStartProgress() method.

**Comment by furkanaskin** [comment]
@jayeshkananidifferenz are you trying to preload them in activity or in start of application like [this](https://github.com/c2mInc/C2MStoryViewer/blob/66afb19e044803488ac7a70ec21b72f20c8c4644/app/src/main/java/com/c2m/storyviewer/screen/MainActivity.kt#L89) function. For better ux you need to show stories asap and maybe you can reduce your image sizes with resizing? or as i said you can try preload stuff.

**Comment by jayeshkananidifferenz** [comment]
> @jayeshkananidifferenz are you trying to preload them in activity or in start of application like [this](https://github.com/c2mInc/C2MStoryViewer/blob/66afb19e044803488ac7a70ec21b72f20c8c4644/app/src/main/java/com/c2m/storyviewer/screen/MainActivity.kt#L89) function. For better ux you need to show stories asap and maybe you can reduce your image sizes with resizing? or as i said you can try preload stuff.

@furkanaskin , Thanks for your response.

I've already implemented preload images method. Still, It's not working perfectly.
Have you any another way for starting the story progressbar after images displayed in imageview control?

**Comment by Cutta** [comment]
Hi @jayeshkananidifferenz 
did you solve it as you wanted?

**Comment by jayeshkananidifferenz** [comment]
> Hi @jayeshkananidifferenz
> did you solve it as you wanted?

Hi @Cutta ,
I have solved this issue.
Actually, Images is starting to load before executing onStartProgress() method. So, I've managed image loading it after called onStartProgress().
And, It's working fine.

Thank you.

**Comment by riyazparasara** [comment]
> > Hi @jayeshkananidifferenz
> > did you solve it as you wanted?
> 
> Hi @Cutta , I have solved this issue. Actually, Images is starting to load before executing onStartProgress() method. So, I've managed image loading it after called onStartProgress(). And, It's working fine.
> 
> Thank you.

Hello @jayeshkananidifferenz 

can you help me how you can solve this issue please ?
